export const nameMapping = {
  "Costa Rica": "Costa Rica",
  "Argelia": "Algeria",
  "Alemania": "Germany",
  "Bélgica": "Belgium",
  "Bosnia y Herzegovina": "Bosnia  Herzegovina",
  "Brasil": "Brazil",
  "Camerún": "Cameroon",
  "Canadá": "Canada",
  "Cabo Verde": "Cape Verde",
  "Costa de Marfil": "Ivory Coast",
  "Croacia": "Croatia",
  "Curazao": "Curacao",
  "Egipto": "Egypt",
  "Inglaterra": "England",
  "Finlandia": "Finland",
  "Francia": "France",
  "Ghana": "Ghana",
  "Grecia": "Greece",
  "Hungría": "Hungary",
  "Irlanda": "Ireland",
  "Italia": "Italy",
  "Japón": "Japan",
  "Jordania": "Jordan",
  "México": "Mexico",
  "Marruecos": "Morocco",
  "Países Bajos": "Netherlands",
  "Irlanda del Norte": "Northern Ireland",
  "Noruega": "Norway",
  "Panamá": "Panama",
  "Perú": "Peru",
  "Rumania": "Romania",
  "Arabia Saudita": "Saudi Arabia",
  "Escocia": "Scotland",
  "Sudáfrica": "South Africa",
  "Corea del Sur": "South Korea",
  "España": "Spain",
  "Suecia": "Sweden",
  "Suiza": "Switzerland",
  "Túnez": "Tunisia",
  "Turquía": "Turkey",
  "Emiratos Árabes": "UAE",
  "Estados Unidos": "USA",
  "Gales": "Wales",
  "República Checa": "Czech Republic",
};